services:
  backend:
    image: openjdk:11
    container_name: backend-tenpo
    build:
      context: ./backend-tenpo
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tenpo
      - SPRING_DATASOURCE_USERNAME=tenpo_user
      - SPRING_DATASOURCE_PASSWORD=tenpo_password
    depends_on:
      - db
    networks:
      - tenpo-network

  frontend:
    build:
      context: ./tenpo-frontend
      dockerfile: Dockerfile
    container_name: tenpo-frontend
    ports:
      - "80:80"
    networks:
      - tenpo-network

  db:
    image: postgres:13
    container_name: tenpo-db
    environment:
      - POSTGRES_DB=tenpo
      - POSTGRES_USER=tenpo_user
      - POSTGRES_PASSWORD=tenpo_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tenpo-network

networks:
  tenpo-network:
    driver: bridge

volumes:
  postgres-data: